name: ESP32 Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install ESP-IDF prerequisites
      run: |
        sudo apt-get update && sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

    - name: Clone ESP-IDF
      run: |
        git clone -b v5.2.2 --recursive https://github.com/espressif/esp-idf.git $GITHUB_WORKSPACE/esp-idf
        cd $GITHUB_WORKSPACE/esp-idf
        ./install.sh

    - name: Build project
      run: |
        source $GITHUB_WORKSPACE/esp-idf/export.sh
        cd src
        idf.py build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: List output files
      run: ls -l ./src/build/
      working-directory: ${{ github.workspace }}

    - name: Upload file to S3
      run: aws s3 cp ./src/build/swarmcom.bin s3://robotics-dissertation/OTA/swarmcom.bin
      working-directory: ${{ github.workspace }}

    - name: Create version JSON
      run: |
        VERSION=$(cat ./src/version.txt)
        echo "{\"version\": \"$VERSION\", \"url\": \"https://robotics-dissertation.s3.eu-north-1.amazonaws.com/OTA/swarmcom.bin\"}" > ./src/build/version.json

    - name: Upload JSON to S3
      run: aws s3 cp ./src/build/version.json s3://robotics-dissertation/OTA/version.json
      working-directory: ${{ github.workspace }}