name: ESP32 Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install ESP-IDF
      run: |
        sudo apt-get update && sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        wget https://github.com/espressif/esp-idf/releases/download/v5.2/esp-idf-v5.2-linux-x86_64.tar.gz
        tar -xzf esp-idf-v5.2-linux-x86_64.tar.gz
        echo "ESP-IDF_PATH=${GITHUB_WORKSPACE}/esp-idf" >> $GITHUB_ENV
        source $ESP-IDF_PATH/export.sh


    - name: Build project
      run: |
        cs src
        idf.py build
